"""web/js/items.js is generated from the Python catalog, and the JS ports say
what the Python says.

- The file on disk equals tools/gen_items_js.py render() (run the tool to fix).
- Under node: discoveredLevel / tierLabel / itemImage agree with shared.items
  for every item, raw byte and level; the tracked range and mode sets agree
  with agent.agent; the effect constants agree with sni/item_effects.py; and
  a replay of grants and revokes through agent.effects.Effects and
  HLEffects.Effects produces the same reads, the same writes in the same
  order, the same results and the same errors.
"""
import importlib.util
import json
import shutil
import subprocess
import unittest
from pathlib import Path

from agent import agent as py_agent
from agent.effects import Effects as PyEffects
from agent.sni import item_effects
from shared.items import ITEMS, discovered_level, item_image, tier_label

ROOT = Path(__file__).resolve().parents[1]
NODE = shutil.which("node")
OUT = ROOT / "web" / "js" / "items.js"


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_items_js", ROOT / "tools" / "gen_items_js.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class GeneratedFileTests(unittest.TestCase):
    def test_items_js_matches_the_catalog(self):
        gen = _load_generator()
        self.assertTrue(OUT.exists(), "web/js/items.js is missing; run tools/gen_items_js.py")
        on_disk = OUT.read_text(encoding="utf-8").replace("\r\n", "\n")
        self.assertEqual(gen.render(), on_disk,
                         "web/js/items.js is out of date; run tools/gen_items_js.py")

    def test_render_is_stable_and_says_it_is_generated(self):
        gen = _load_generator()
        text = gen.render()
        self.assertEqual(text, gen.render())
        self.assertIn("GENERATED by tools/gen_items_js.py", text)
        self.assertNotIn("\r", text)
        for it in ITEMS:
            self.assertIn('key: "%s"' % it.key, text)


# ---- parity under node --------------------------------------------------

LEVELS = [-1, 0, 1, 2, 3, 4, 5]
EFFECT_CONSTANTS = [
    "BOOTS_ADDR", "ABILITY_ADDR", "RUN_ABILITY_MASK", "ARROWS_ADDR", "DEFAULT_ARROWS",
    "BOOM_EQUIP_ADDR", "POWDER_EQUIP_ADDR", "FLUTE_EQUIP_ADDR", "BOOM_BLUE_BIT", "BOOM_RED_BIT",
    "MUSHROOM_BITS", "MUSHROOM_OWN", "POWDER_BIT", "SHOVEL_BIT", "FLUTE_ACTIVE_BIT",
    "FLUTE_INACTIVE_BIT", "FLUTE_ANY_BITS",
]

PARITY_JS = r"""
const path = require('path');
const root = process.argv[1];
const I = require(path.join(root, 'web', 'js', 'items.js'));
const E = require(path.join(root, 'web', 'js', 'effects.js'));
const plan = JSON.parse(require('fs').readFileSync(0, 'utf8'));
(async () => {
  const out = { levels: {}, labels: {}, images: {}, effects: {}, catalog: {}, scenarios: [] };
  for (const it of I.ITEMS) {
    const row = [];
    for (let raw = 0; raw < 256; raw++) row.push(I.discoveredLevel(it, raw));
    out.levels[it.key] = row;
    out.labels[it.key] = plan.levels.map(l => I.tierLabel(it, l));
    out.images[it.key] = plan.levels.map(l => I.itemImage(it.key, l));
  }
  for (const k of plan.constants) out.effects[k] = E[k];
  out.catalog = {
    keys: I.ITEMS.map(it => it.key),
    start: I.TRACKED_START, size: I.TRACKED_SIZE, mode: I.GAME_MODE_ADDR,
    addrs: I.TRACKED_ADDRS,
    playable: Object.keys(I.PLAYABLE_MODES).map(Number).sort((a, b) => a - b),
    out_of_game: Object.keys(I.OUT_OF_GAME_MODES).map(Number).sort((a, b) => a - b)
  };
  for (const sc of plan.scenarios) {
    const mem = new Map(sc.mem);
    let drops = 0;
    const ops = [];
    const t = {
      read: async (addr, len) => {
        ops.push(['r', addr, len]);
        if (drops > 0) { drops--; return null; }
        const b = new Uint8Array(len);
        for (let i = 0; i < len; i++) b[i] = mem.get(addr + i) || 0;
        return b;
      },
      write: async (addr, bytes) => {
        ops.push(['w', addr, Array.from(bytes)]);
        if (sc.readonly) return false;
        bytes.forEach((v, i) => mem.set(addr + i, v));
        return true;
      }
    };
    const fx = new E.Effects(t);
    const results = [];
    for (const [op, key, level, d] of sc.steps) {
      if (d != null) drops = d;
      try { results.push(op === 'enable' ? await fx.enable(key, level) : await fx.disable(key)); }
      catch (e) { results.push('error: ' + e.message); }
    }
    out.scenarios.push({ ops, results, mem: [...mem.entries()].sort((a, b) => a[0] - b[0]) });
  }
  process.stdout.write(JSON.stringify(out));
})();
"""


class RecordingTransport:
    """tests.test_effects.MemoryTransport + FlakyReadTransport, logging every call."""

    def __init__(self, mem, readonly=False):
        self.connected = True
        self.memory = dict(mem)
        self.readonly = readonly
        self.drops = 0
        self.ops = []

    def read_memory(self, address, size=1, domain="WRAM"):
        self.ops.append(["r", address, size])
        if self.drops > 0:
            self.drops -= 1
            return None
        return bytes(self.memory.get(address + i, 0) for i in range(size))

    def write_memory(self, address, data, domain="WRAM"):
        self.ops.append(["w", address, list(data)])
        if self.readonly:
            return False
        for i, b in enumerate(data):
            self.memory[address + i] = b
        return True


def _scenarios():
    sweep = []
    for it in ITEMS:
        top = it.cap if it.kind in ("progressive", "bow") else 1
        for level in range(1, top + 1):
            sweep.append(["enable", it.key, level, None])
        sweep.append(["disable", it.key, 0, None])
    pairs = [("shovel", "flute"), ("mushroom", "powder"), ("blue_boomerang", "red_boomerang")]
    for a, b in pairs:
        for x, y in ((a, b), (b, a)):
            sweep += [["enable", x, 1, None], ["enable", y, 1, None],
                      ["disable", y, 0, None], ["disable", x, 0, None]]
            sweep += [["enable", x, 1, None], ["enable", y, 1, None],
                      ["disable", x, 0, None], ["disable", y, 0, None]]
    sweep += [["enable", "bow", 2, None], ["enable", "bow", 1, None], ["enable", "bow", 2, None],
              ["disable", "bow", 0, None], ["enable", "sword", 3, None], ["enable", "sword", 1, None],
              ["disable", "sword", 0, None]]
    readonly = []
    for it in ITEMS:
        readonly += [["enable", it.key, it.cap, None], ["disable", it.key, 0, None]]
    drops = [
        ["enable", "boots", 1, 3],        # absorbed by the retries
        ["disable", "boots", 0, 0],
        ["enable", "boots", 1, 1000],     # never readable: abort, no clobber
        ["enable", "flute", 1, 0],
        ["disable", "flute", 0, 5],
        ["enable", "bow", 2, 6],          # BowTracking unreadable: nothing written
        ["enable", "bow", 2, 0],
    ]
    return [
        {"mem": [[0xF379, 0x68], [0xF38E, 0x05], [0xF38C, 0x08]], "steps": sweep},
        {"mem": [[0xF379, 0x68], [0xF359, 2]], "steps": readonly, "readonly": True},
        {"mem": [[0xF379, 0x68], [0xF377, 7]], "steps": drops},
    ]


def _python_side(scenarios):
    out = []
    for sc in scenarios:
        t = RecordingTransport(dict((a, v) for a, v in sc["mem"]), readonly=sc.get("readonly", False))
        fx = PyEffects(t)
        results = []
        for op, key, level, d in sc["steps"]:
            if d is not None:
                t.drops = d
            try:
                results.append(fx.enable(key, level) if op == "enable" else fx.disable(key))
            except IOError as e:
                results.append("error: " + str(e).replace("[ItemEffects] ", ""))
        out.append({"ops": t.ops, "results": results,
                    "mem": [[a, v] for a, v in sorted(t.memory.items())]})
    return out


@unittest.skipIf(NODE is None, "node is not installed")
class ParityTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.scenarios = _scenarios()
        plan = {"levels": LEVELS, "constants": EFFECT_CONSTANTS, "scenarios": cls.scenarios}
        done = subprocess.run([NODE, "-e", PARITY_JS, str(ROOT)], input=json.dumps(plan),
                              capture_output=True, text=True, encoding="utf-8", timeout=60)
        if done.returncode != 0:
            raise AssertionError(done.stdout + done.stderr)
        cls.js = json.loads(done.stdout)

    def test_discovered_level_for_every_item_and_byte(self):
        for it in ITEMS:
            with self.subTest(it.key):
                self.assertEqual(self.js["levels"][it.key], [discovered_level(it, r) for r in range(256)])

    def test_tier_label_and_item_image(self):
        for it in ITEMS:
            with self.subTest(it.key):
                self.assertEqual(self.js["labels"][it.key], [tier_label(it, lv) for lv in LEVELS])
                self.assertEqual(self.js["images"][it.key], [item_image(it.key, lv) for lv in LEVELS])

    def test_catalog_and_modes_match_the_python_agent(self):
        cat = self.js["catalog"]
        self.assertEqual(cat["keys"], [it.key for it in ITEMS])
        self.assertEqual(cat["start"], py_agent._TRACKED_START)
        self.assertEqual(cat["size"], py_agent._TRACKED_SIZE)
        self.assertEqual(cat["addrs"], py_agent._TRACKED_ADDRS)
        self.assertEqual(cat["mode"], py_agent.GAME_MODE_ADDR)
        self.assertEqual(cat["playable"], sorted(py_agent.PLAYABLE_MODES))
        self.assertEqual(cat["out_of_game"], sorted(py_agent.OUT_OF_GAME_MODES))

    def test_effect_constants_match_item_effects(self):
        for name in EFFECT_CONSTANTS:
            with self.subTest(name):
                self.assertEqual(self.js["effects"][name], getattr(item_effects, name))

    def test_grants_and_revokes_are_the_same_writes_in_the_same_order(self):
        py = _python_side(self.scenarios)
        for i, (want, got) in enumerate(zip(py, self.js["scenarios"])):
            with self.subTest(scenario=i):
                self.assertEqual(got["results"], want["results"])
                self.assertEqual(got["ops"], want["ops"])
                self.assertEqual(got["mem"], want["mem"])
        # the scenarios exercise what they claim to
        self.assertTrue(any(isinstance(r, str) and "verification failed" in r for r in py[1]["results"]))
        self.assertIn("error: could not read WRAM $F379", py[2]["results"])
        self.assertIn("error: could not read WRAM $F38E", py[2]["results"])


if __name__ == "__main__":
    unittest.main()
