/* BombosSwap - the item catalog, for the browser.
 *
 * GENERATED by tools/gen_items_js.py from shared/items.py and
 * agent/sni/memory_constants.py. Do not edit this file: change the Python
 * catalog and run
 *
 *   F:\HyruleLink\.venv\Scripts\python.exe tools\gen_items_js.py
 *
 * tests/test_items_js.py fails when this file and the catalog disagree.
 *
 * Addresses are WRAM offsets ($7E0000 + addr). Kinds: simple (0 absent, else
 * `give`), progressive (the byte is the tier), bitfield (one bit of a shared
 * byte), boots (plus the run flag), bow (BowTracking $7EF38E: 0x80 has,
 * 0x40 silver). Mode sets are objects keyed by number, as in snes.js.
 */
(function (root) {
  'use strict';

  var ITEMS = [
    { key: "sword", name: "Sword", addr: 0xF359, kind: "progressive", mask: 0xFF, cap: 4, present: 1, give: 1, effect_key: null, tiers: ["none", "Fighter", "Master", "Tempered", "Gold"] },
    { key: "shield", name: "Shield", addr: 0xF35A, kind: "progressive", mask: 0xFF, cap: 3, present: 1, give: 1, effect_key: null, tiers: ["none", "Fighter", "Fire", "Mirror"] },
    { key: "armor", name: "Mail", addr: 0xF35B, kind: "progressive", mask: 0xFF, cap: 2, present: 1, give: 1, effect_key: null, tiers: ["Green", "Blue", "Red"] },
    { key: "gloves", name: "Gloves", addr: 0xF354, kind: "progressive", mask: 0xFF, cap: 2, present: 1, give: 1, effect_key: null, tiers: ["none", "Power Glove", "Titan's Mitt"] },
    { key: "bow", name: "Bow", addr: 0xF38E, kind: "bow", mask: 0xFF, cap: 2, present: 1, give: 1, effect_key: "bow", tiers: ["none", "Bow", "Silver Bow"] },
    { key: "magic", name: "Magic Upgrade", addr: 0xF37B, kind: "progressive", mask: 0xFF, cap: 2, present: 1, give: 1, effect_key: null, tiers: ["none", "1/2 Magic", "1/4 Magic"] },
    { key: "boots", name: "Pegasus Boots", addr: 0xF355, kind: "boots", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: "boots", tiers: [] },
    { key: "hookshot", name: "Hookshot", addr: 0xF342, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "firerod", name: "Fire Rod", addr: 0xF345, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "icerod", name: "Ice Rod", addr: 0xF346, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "bombos", name: "Bombos Medallion", addr: 0xF347, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "ether", name: "Ether Medallion", addr: 0xF348, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "quake", name: "Quake Medallion", addr: 0xF349, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "lamp", name: "Lamp", addr: 0xF34A, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "hammer", name: "Magic Hammer", addr: 0xF34B, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "bug_net", name: "Bug Net", addr: 0xF34D, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "book", name: "Book of Mudora", addr: 0xF34E, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "somaria", name: "Cane of Somaria", addr: 0xF350, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "byrna", name: "Cane of Byrna", addr: 0xF351, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "cape", name: "Magic Cape", addr: 0xF352, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "mirror", name: "Magic Mirror", addr: 0xF353, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 2, effect_key: null, tiers: [] },
    { key: "flippers", name: "Flippers", addr: 0xF356, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "moon_pearl", name: "Moon Pearl", addr: 0xF357, kind: "simple", mask: 0xFF, cap: 1, present: 1, give: 1, effect_key: null, tiers: [] },
    { key: "blue_boomerang", name: "Blue Boomerang", addr: 0xF38C, kind: "bitfield", mask: 0x80, cap: 1, present: 1, give: 1, effect_key: "blue_boomerang", tiers: [] },
    { key: "red_boomerang", name: "Red Boomerang", addr: 0xF38C, kind: "bitfield", mask: 0x40, cap: 1, present: 1, give: 1, effect_key: "red_boomerang", tiers: [] },
    { key: "mushroom", name: "Mushroom", addr: 0xF38C, kind: "bitfield", mask: 0x20, cap: 1, present: 1, give: 1, effect_key: "mushroom", tiers: [] },
    { key: "powder", name: "Magic Powder", addr: 0xF38C, kind: "bitfield", mask: 0x10, cap: 1, present: 1, give: 1, effect_key: "powder", tiers: [] },
    { key: "shovel", name: "Shovel", addr: 0xF38C, kind: "bitfield", mask: 0x04, cap: 1, present: 1, give: 1, effect_key: "shovel", tiers: [] },
    { key: "flute", name: "Flute", addr: 0xF38C, kind: "bitfield", mask: 0x03, cap: 1, present: 1, give: 1, effect_key: "flute", tiers: [] }
  ];

  var BOW_FLAGS_ADDR = 0xF38E;
  var BOW_HAS_MASK = 0x80;
  var BOW_SILVER_MASK = 0x40;
  var BOW_EQUIP_ADDR = 0xF340;
  var INV_TRACK_ADDR = 0xF38C;
  var ITEM_IMAGE_TIERS = { "sword": 4, "shield": 3, "armor": 2, "gloves": 2, "bow": 2 };

  var GAME_MODE_ADDR = 0x0010;
  var PLAYABLE_MODES = { 0x06: 1, 0x07: 1, 0x08: 1, 0x09: 1, 0x0A: 1, 0x0B: 1, 0x0E: 1 };
  var OUT_OF_GAME_MODES = { 0x00: 1, 0x01: 1, 0x02: 1, 0x03: 1, 0x04: 1, 0x05: 1, 0x14: 1, 0x17: 1, 0x1B: 1 };

  /* every item address, ascending; the agent reads [start, start + size) in one go */
  var TRACKED_ADDRS = [0xF342, 0xF345, 0xF346, 0xF347, 0xF348, 0xF349, 0xF34A, 0xF34B, 0xF34D, 0xF34E, 0xF350, 0xF351, 0xF352, 0xF353, 0xF354, 0xF355, 0xF356, 0xF357, 0xF359, 0xF35A, 0xF35B, 0xF37B, 0xF38C, 0xF38E];
  var TRACKED_START = 0xF342;
  var TRACKED_SIZE = 77;

  var BY_KEY = {};
  var ITEMS_BY_ADDR = {};
  ITEMS.forEach(function (it) {
    BY_KEY[it.key] = it;
    (ITEMS_BY_ADDR[it.addr] = ITEMS_BY_ADDR[it.addr] || []).push(it);
  });

  function lookup(item) {
    if (typeof item !== 'string') return item;
    if (!Object.prototype.hasOwnProperty.call(BY_KEY, item)) throw new Error('unknown item ' + item);
    return BY_KEY[item];
  }

  /* A raw WRAM byte -> this item's level; 0 = not present (shared.items.discovered_level). */
  function discoveredLevel(item, raw) {
    item = lookup(item);
    if (item.kind === 'bitfield') return (raw & item.mask) ? 1 : 0;
    if (item.kind === 'bow') {
      if (!(raw & BOW_HAS_MASK)) return 0;
      return (raw & BOW_SILVER_MASK) ? 2 : 1;
    }
    if (item.kind === 'boots' || item.kind === 'simple') return raw ? 1 : 0;
    if (raw < item.present) return 0;
    return Math.min(raw, item.cap);
  }

  /* Label for a level (shared.items.tier_label). */
  function tierLabel(item, level) {
    item = lookup(item);
    if (item.tiers.length && level >= 0 && level < item.tiers.length) return item.tiers[level];
    return level > 0 ? 'owned' : '\u2014';
  }

  /* File name within web/items/ (shared.items.item_image). */
  function itemImage(key, level) {
    var maxtier = Object.prototype.hasOwnProperty.call(ITEM_IMAGE_TIERS, key) ? ITEM_IMAGE_TIERS[key] : 0;
    if (maxtier) return key + '-' + Math.min(Math.max(level || 0, 1), maxtier) + '.png';
    return key + '.png';
  }

  var HLItems = {
    ITEMS: ITEMS, BY_KEY: BY_KEY, ITEMS_BY_ADDR: ITEMS_BY_ADDR,
    BOW_FLAGS_ADDR: BOW_FLAGS_ADDR, BOW_HAS_MASK: BOW_HAS_MASK, BOW_SILVER_MASK: BOW_SILVER_MASK,
    BOW_EQUIP_ADDR: BOW_EQUIP_ADDR, INV_TRACK_ADDR: INV_TRACK_ADDR, ITEM_IMAGE_TIERS: ITEM_IMAGE_TIERS,
    GAME_MODE_ADDR: GAME_MODE_ADDR, PLAYABLE_MODES: PLAYABLE_MODES, OUT_OF_GAME_MODES: OUT_OF_GAME_MODES,
    TRACKED_ADDRS: TRACKED_ADDRS, TRACKED_START: TRACKED_START, TRACKED_SIZE: TRACKED_SIZE,
    discoveredLevel: discoveredLevel, tierLabel: tierLabel, itemImage: itemImage
  };
  root.HLItems = HLItems;
  if (typeof module === 'object' && module.exports) module.exports = HLItems;
})(typeof window !== 'undefined' ? window : globalThis);
