"""Generate web/js/items.js from the Python item catalog.

The browser client needs the same catalog the server and the Python agent use:
every item's address, kind, mask, tiers, and the game-mode sets that say when a
save is loaded. `shared/items.py` and `agent/sni/memory_constants.py` stay the
single source; this script writes them out as a UMD module (`HLItems`), and
tests/test_items_js.py fails when the file on disk and render() disagree.

    F:\\HyruleLink\\.venv\\Scripts\\python.exe tools\\gen_items_js.py          # write it
    F:\\HyruleLink\\.venv\\Scripts\\python.exe tools\\gen_items_js.py --check  # exit 1 on drift

Run from anywhere; the repo root is put on sys.path so `shared` imports.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from shared import items as I                   # noqa: E402
from agent.sni import memory_constants as M     # noqa: E402

OUT = ROOT / "web" / "js" / "items.js"


def _hex(n, width=4):
    return "0x%0*X" % (width, n)


def _str(s):
    return json.dumps(s)


def _modes(values):
    return "{ " + ", ".join("%s: 1" % _hex(v, 2) for v in sorted(values)) + " }"


def _item(it):
    tiers = "[" + ", ".join(_str(t) for t in it.tiers) + "]"
    return ("{ key: %s, name: %s, addr: %s, kind: %s, mask: %s, cap: %d, present: %d, "
            "give: %d, effect_key: %s, tiers: %s }") % (
        _str(it.key), _str(it.name), _hex(it.addr), _str(it.kind), _hex(it.mask, 2),
        it.cap, it.present, it.give,
        _str(it.effect_key) if it.effect_key is not None else "null", tiers)


def render() -> str:
    addrs = sorted({it.addr for it in I.ITEMS})
    start, size = addrs[0], addrs[-1] - addrs[0] + 1
    image_tiers = ", ".join("%s: %d" % (_str(k), v) for k, v in I.ITEM_IMAGE_TIERS.items())
    items = ",\n".join("    " + _item(it) for it in I.ITEMS)
    tracked = ", ".join(_hex(a) for a in addrs)
    return _TEMPLATE.format(
        items=items,
        bow_flags=_hex(I.BOW_FLAGS_ADDR), bow_has=_hex(I.BOW_HAS_MASK, 2),
        bow_silver=_hex(I.BOW_SILVER_MASK, 2), bow_equip=_hex(I.BOW_EQUIP_ADDR),
        inv_track=_hex(I.INV_TRACK_ADDR), image_tiers=image_tiers,
        game_mode=_hex(M.MEMORY_ADDRESSES["game_mode"]),
        playable=_modes(M.PLAYABLE_MODES), out_of_game=_modes(M.OUT_OF_GAME_MODES),
        tracked=tracked, start=_hex(start), size=size,
    )


# Doubled braces are literal JS braces (str.format).
_TEMPLATE = """\
/* BombosSwap - the item catalog, for the browser.
 *
 * GENERATED by tools/gen_items_js.py from shared/items.py and
 * agent/sni/memory_constants.py. Do not edit this file: change the Python
 * catalog and run
 *
 *   F:\\HyruleLink\\.venv\\Scripts\\python.exe tools\\gen_items_js.py
 *
 * tests/test_items_js.py fails when this file and the catalog disagree.
 *
 * Addresses are WRAM offsets ($7E0000 + addr). Kinds: simple (0 absent, else
 * `give`), progressive (the byte is the tier), bitfield (one bit of a shared
 * byte), boots (plus the run flag), bow (BowTracking $7EF38E: 0x80 has,
 * 0x40 silver). Mode sets are objects keyed by number, as in snes.js.
 */
(function (root) {{
  'use strict';

  var ITEMS = [
{items}
  ];

  var BOW_FLAGS_ADDR = {bow_flags};
  var BOW_HAS_MASK = {bow_has};
  var BOW_SILVER_MASK = {bow_silver};
  var BOW_EQUIP_ADDR = {bow_equip};
  var INV_TRACK_ADDR = {inv_track};
  var ITEM_IMAGE_TIERS = {{ {image_tiers} }};

  var GAME_MODE_ADDR = {game_mode};
  var PLAYABLE_MODES = {playable};
  var OUT_OF_GAME_MODES = {out_of_game};

  /* every item address, ascending; the agent reads [start, start + size) in one go */
  var TRACKED_ADDRS = [{tracked}];
  var TRACKED_START = {start};
  var TRACKED_SIZE = {size};

  var BY_KEY = {{}};
  var ITEMS_BY_ADDR = {{}};
  ITEMS.forEach(function (it) {{
    BY_KEY[it.key] = it;
    (ITEMS_BY_ADDR[it.addr] = ITEMS_BY_ADDR[it.addr] || []).push(it);
  }});

  function lookup(item) {{
    if (typeof item !== 'string') return item;
    if (!Object.prototype.hasOwnProperty.call(BY_KEY, item)) throw new Error('unknown item ' + item);
    return BY_KEY[item];
  }}

  /* A raw WRAM byte -> this item's level; 0 = not present (shared.items.discovered_level). */
  function discoveredLevel(item, raw) {{
    item = lookup(item);
    if (item.kind === 'bitfield') return (raw & item.mask) ? 1 : 0;
    if (item.kind === 'bow') {{
      if (!(raw & BOW_HAS_MASK)) return 0;
      return (raw & BOW_SILVER_MASK) ? 2 : 1;
    }}
    if (item.kind === 'boots' || item.kind === 'simple') return raw ? 1 : 0;
    if (raw < item.present) return 0;
    return Math.min(raw, item.cap);
  }}

  /* Label for a level (shared.items.tier_label). */
  function tierLabel(item, level) {{
    item = lookup(item);
    if (item.tiers.length && level >= 0 && level < item.tiers.length) return item.tiers[level];
    return level > 0 ? 'owned' : '\\u2014';
  }}

  /* File name within web/items/ (shared.items.item_image). */
  function itemImage(key, level) {{
    var maxtier = Object.prototype.hasOwnProperty.call(ITEM_IMAGE_TIERS, key) ? ITEM_IMAGE_TIERS[key] : 0;
    if (maxtier) return key + '-' + Math.min(Math.max(level || 0, 1), maxtier) + '.png';
    return key + '.png';
  }}

  var HLItems = {{
    ITEMS: ITEMS, BY_KEY: BY_KEY, ITEMS_BY_ADDR: ITEMS_BY_ADDR,
    BOW_FLAGS_ADDR: BOW_FLAGS_ADDR, BOW_HAS_MASK: BOW_HAS_MASK, BOW_SILVER_MASK: BOW_SILVER_MASK,
    BOW_EQUIP_ADDR: BOW_EQUIP_ADDR, INV_TRACK_ADDR: INV_TRACK_ADDR, ITEM_IMAGE_TIERS: ITEM_IMAGE_TIERS,
    GAME_MODE_ADDR: GAME_MODE_ADDR, PLAYABLE_MODES: PLAYABLE_MODES, OUT_OF_GAME_MODES: OUT_OF_GAME_MODES,
    TRACKED_ADDRS: TRACKED_ADDRS, TRACKED_START: TRACKED_START, TRACKED_SIZE: TRACKED_SIZE,
    discoveredLevel: discoveredLevel, tierLabel: tierLabel, itemImage: itemImage
  }};
  root.HLItems = HLItems;
  if (typeof module === 'object' && module.exports) module.exports = HLItems;
}})(typeof window !== 'undefined' ? window : globalThis);
"""


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    text = render()
    if "--check" in argv:
        have = OUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUT.exists() else ""
        if have != text:
            print("web/js/items.js is out of date; run tools/gen_items_js.py")
            return 1
        print("web/js/items.js is up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d items)" % (OUT.relative_to(ROOT), len(I.ITEMS)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
